# Generated by Django 5.1.6 on 2025-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='redeem_code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
