# Generated by Django 5.2 on 2025-04-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_store_redeem_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='coupon_detail',
        ),
        migrations.RemoveField(
            model_name='store',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='store',
            name='redeem_code',
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_detail', models.TextField()),
                ('expiry_date', models.DateTimeField()),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeem_code', models.CharField(blank=True, max_length=6, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
        ),
    ]
