# Generated by Django 5.1.6 on 2025-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coupon_source_user_alter_coupon_redeemed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
