# Generated by Django 5.1.6 on 2025-05-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_passwordresetprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='estimated_savings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated amount saved in TWD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='coupons_used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_savings_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='savings_goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='savings_goal_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='savings_goal_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
