# Generated by Django 5.1.6 on 2025-05-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_completedgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDrawCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_draw', to='api.coupon')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
