# Generated by Django 5.1.6 on 2025-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dailydrawcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydrawcoupon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
