# Generated by Django 5.1.6 on 2025-05-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dailydrawcoupon_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coupon'),
        ),
    ]
