# Generated by Django 5.1.6 on 2025-05-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_log_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
