# Generated by Django 5.1.6 on 2025-05-17 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_coupon_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_redeemed',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='redeemed_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='redeemed_by',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='source_user',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='business_hours',
        ),
        migrations.AddField(
            model_name='coupon',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='original_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='business_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CouponTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100)),
                ('coupon_detail', models.TextField()),
                ('important_notes', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('remaining_quantity', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('draw_probability', models.FloatField(default=0.1, help_text='Probability (0-1) of successful draw')),
                ('draw_limit_per_day', models.PositiveIntegerField(default=1, help_text='How many times a user can draw per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_templates', to='api.store')),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='api.coupontemplate'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('savings_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coupon_type', models.CharField(editable=False, max_length=20)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('coupon_type', 'exclusive')), fields=('coupon', 'user'), name='unique_exclusive_coupon_redemption')],
            },
        ),
    ]
