# Generated by Django 5.1.6 on 2025-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_coupon_is_redeemed_remove_coupon_redeemed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupontemplate',
            name='draw_limit_per_day',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_draw_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupontemplate',
            name='draw_probability',
            field=models.FloatField(default=0.5, help_text='Probability (0-1) of successful draw'),
        ),
        migrations.DeleteModel(
            name='DailyDrawCoupon',
        ),
    ]
