# Generated by Django 5.1.6 on 2025-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_coupon_last_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontemplate',
            name='template_redeem_code',
            field=models.CharField(blank=True, help_text='Template redeem code for exclusive coupons', max_length=6, null=True),
        ),
    ]
