# Generated by Django 5.1.6 on 2025-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_coupontemplate_template_redeem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
