# Generated by Django 5.1.6 on 2025-05-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_studentprofile_last_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_per_day',
            field=models.CharField(choices=[('store', '隨取及用'), ('exclusive', '專屬優惠')], default='unlimited', help_text='How many times this coupon can be used per day', max_length=10),
        ),
    ]
