# Generated by Django 5.1.6 on 2025-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_coupon_usage_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_per_day',
            field=models.CharField(choices=[('one-time', '每日單次'), ('unlimited', '每日無限制')], default='unlimited', help_text='How many times this coupon can be used per day', max_length=10),
        ),
    ]
