# Generated by Django 5.2 on 2025-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_coupon_usage_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='api.tag'),
        ),
        migrations.AddField(
            model_name='coupontemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='coupon_templates', to='api.tag'),
        ),
    ]
