# Generated by Django 5.2 on 2025-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tag_studentprofile_phone_number_coupon_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.CharField(blank=True, choices=[('restaurant', '餐飲'), ('retail', '零售'), ('service', '服務'), ('entertainment', '娛樂'), ('beauty', '美容'), ('education', '教育'), ('medical', '醫療'), ('other', '其他')], max_length=20, null=True),
        ),
    ]
