# Generated by Django 5.2 on 2025-12-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_store_image_url_store_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude of redemption location', null=True),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude of redemption location', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude of action location', null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='lng',
            field=models.FloatField(blank=True, help_text='Longitude of action location', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='average_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average order value in TWD for GMV calculation', max_digits=10, null=True),
        ),
    ]
