# Generated by Django 5.2 on 2025-12-11 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_store_image_url_store_store_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsharerequest',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, coupon is shared to public pool'),
        ),
        migrations.AddConstraint(
            model_name='couponsharerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', True), ('status', 'pending')), fields=('coupon',), name='unique_pending_public_share_per_coupon'),
        ),
    ]
