# Generated by Django 5.2 on 2025-12-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_couponredemption_lat_couponredemption_lng_log_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.coupontemplate'),
        ),
    ]
