# Generated by Django 5.2 on 2025-12-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_couponsharerequest_is_public_and_more'),
        ('api', '0027_log_template'),
    ]

    operations = [
    ]
