# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20251229_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='acquisition_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('draw', '抽優惠券'),
                    ('consolidate', '電話歸戶'),
                    ('transfer', '私人轉讓'),
                    ('public_pool', '公共池領取'),
                ],
                help_text='How the coupon was acquired by the current holder',
                max_length=20,
                null=True
            ),
        ),
    ]


