# Generated by Django 5.2 on 2026-01-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20251228_2114'),
        ('api', '0029_coupon_acquisition_method'),
    ]

    operations = [
    ]
