# Generated by Django 5.2 on 2026-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20260105_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='pending_phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Phone number for pending (unclaimed) coupons sent to unregistered users', max_length=20, null=True),
        ),
    ]
