# Generated by Django 5.2 on 2026-01-07 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_coupon_pending_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Taiwan mobile number in 09XXXXXXXX format', max_length=20)),
                ('otp_code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When OTP was generated')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires (created_at + 10 minutes)')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of verification attempts (max 5)')),
                ('is_verified', models.BooleanField(default=False, help_text='True if OTP was successfully verified')),
                ('user', models.ForeignKey(help_text='User requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='phone_otp_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'created_at'], name='api_phoneotp_phone_created_idx'), models.Index(fields=['user', 'created_at'], name='api_phoneotp_user_created_idx')],
            },
        ),
    ]
