# Generated by Django 5.2 on 2026-01-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_phonootprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='unified_redeem_code',
            field=models.CharField(blank=True, help_text='Unified redemption code for all coupons from this store (6-digit numeric format)', max_length=6, null=True, unique=True),
        ),
    ]
