# Generated by Django 5.2 on 2026-01-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_add_unified_redeem_code_to_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='acquisition_method',
            field=models.CharField(blank=True, choices=[('draw', '抽優惠券'), ('consolidate', '電話歸戶'), ('transfer', '私人轉讓'), ('public_pool', '公共池領取'), ('qr_claim', 'QR Code 領取')], help_text='How the coupon was acquired by the current holder', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='QRCodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(help_text='Unique token encoded in QR code (UUID4 format)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is still valid')),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='When the session was invalidated', null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='api.coupontemplate')),
            ],
            options={
                'db_table': 'api_qrcode_session',
                'indexes': [models.Index(fields=['session_token'], name='qr_session_token_idx'), models.Index(fields=['template', 'is_active'], name='qr_session_template_active_idx'), models.Index(fields=['merchant', 'is_active'], name='qr_session_merchant_active_idx')],
            },
        ),
    ]
