# Generated by Django 5.2 on 2026-01-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_coupon_acquisition_method_qrcodesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate claims', max_length=64, unique=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True, help_text='When the coupon was claimed')),
                ('session_token', models.CharField(help_text='Session token from QR code', max_length=255)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_claim_record', to='api.coupon')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_claims', to='api.coupontemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_qrcode_claim',
                'indexes': [
                    models.Index(fields=['idempotency_key'], name='qr_claim_idempotency_key_idx'),
                    models.Index(fields=['user', 'template'], name='qr_claim_user_template_idx'),
                ],
            },
        ),
    ]
