# Generated by Django 5.2 on 2026-01-15 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_qrcode_claim_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_user_email', models.EmailField(max_length=254)),
                ('deleted_user_id', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.CharField(default='user_requested', max_length=255)),
                ('stores_anonymized', models.IntegerField(default=0)),
                ('coupons_preserved', models.IntegerField(default=0)),
                ('initiated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'account_deletion_log',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Merchant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
