# Generated by Django 5.2 on 2026-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_account_deletion_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
