# Generated by Django 5.2 on 2026-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_allow_null_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='verification_email_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
