# Generated by Django 5.2 on 2026-01-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merchantprofile_email_verification_token_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='suspension_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for suspension review'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='suspension_flagged_at',
            field=models.DateTimeField(blank=True, help_text='When flagged for suspension', null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='violation_count',
            field=models.PositiveIntegerField(default=0, help_text='Denormalized violation counter'),
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, help_text='ID of the reported content')),
                ('reason', models.CharField(choices=[('inappropriate', '不當內容'), ('misleading', '誤導資訊'), ('illegal', '違法商品'), ('spam', '垃圾訊息'), ('other', '其他')], help_text='Report reason category', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional additional details')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('reviewed', '已審核'), ('dismissed', '已駁回')], db_index=True, default='pending', help_text='Report processing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When report was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When report was reviewed', null=True)),
                ('content_type', models.ForeignKey(help_text='Django ContentType for generic relation', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(help_text='Consumer who submitted the report', on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EULAAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="EULA version string (e.g., '1.0.0')", max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='When acceptance occurred')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address at acceptance')),
                ('merchant', models.ForeignKey(help_text='Merchant who accepted', on_delete=django.db.models.deletion.CASCADE, related_name='eula_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '核准'), ('remove', '移除內容'), ('suspend', '暫停帳號')], help_text='Action type taken', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes/justification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When action was taken')),
                ('admin', models.ForeignKey(help_text='Admin who took action', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Associated report', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.contentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('content_removed', '內容移除'), ('account_suspended', '帳號暫停')], help_text='Type of violation', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When violation was recorded')),
                ('action', models.ForeignKey(blank=True, help_text='Action that created violation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='api.moderationaction')),
                ('merchant', models.ForeignKey(help_text='Merchant with violation', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, help_text='Originating report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='api.contentreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When block was created')),
                ('store', models.ForeignKey(help_text='Blocked merchant store', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='api.store')),
                ('user', models.ForeignKey(help_text='Consumer who blocked', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'store')},
            },
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['status', 'created_at'], name='report_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreport',
            index=models.Index(fields=['reporter', 'content_type', 'object_id'], name='report_reporter_content_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eulaacceptance',
            unique_together={('merchant', 'version')},
        ),
    ]
