# Generated by Django 5.2 on 2026-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_ugc_compliance_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
