# Generated by Django 5.2 on 2026-02-05 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_ugc_compliance_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotprecord',
            name='purpose',
            field=models.CharField(choices=[('phone_change', 'Phone Change'), ('registration', 'Registration'), ('password_reset', 'Password Reset')], default='phone_change', help_text='Purpose of this OTP (phone_change, registration, password_reset)', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='True if phone was verified via OTP'),
        ),
        migrations.AlterField(
            model_name='phoneotprecord',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User requesting verification (null for registration OTPs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_otp_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
