# Generated by Django 5.2 on 2026-03-12 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_platform_voucher_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='application_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='application_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='application_status',
            field=models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='application_submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
