# Generated by Django 5.2 on 2026-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_merchantprofile_application_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='referral_progress_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sharing_progress_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='couponsharerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platformvoucher',
            name='acquisition_method',
            field=models.CharField(blank=True, choices=[('platform_issue', 'Platform Issue'), ('transfer', 'Transfer'), ('public_pool', 'Public Pool'), ('reward', 'Reward')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
