# Generated by Django 5.2 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_progress_tracker_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sharing_rewards_earned',
            field=models.IntegerField(default=0),
        ),
    ]
