# Generated by Django 5.2 on 2026-04-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_studentprofile_sharing_rewards_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='acquisition_method',
            field=models.CharField(blank=True, choices=[('draw', '抽優惠券'), ('consolidate', '電話歸戶'), ('transfer', '私人轉讓'), ('public_pool', '公共池領取'), ('qr_claim', 'QR Code 領取'), ('admin_issue', '後台發放')], help_text='How the coupon was acquired by the current holder', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WebRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, help_text='The QRCodeSession.session_token from the scanned table QR', max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Populated when user enters phone on points screen', max_length=20, null=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='web_redemptions', to='api.coupontemplate')),
            ],
            options={
                'db_table': 'api_web_redemption',
            },
        ),
    ]
