# Generated by Django 5.2 on 2026-04-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_web_redemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFixedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_session', to='api.store')),
            ],
            options={
                'db_table': 'api_store_fixed_session',
                'indexes': [models.Index(fields=['session_token'], name='store_fixed_session_token_idx'), models.Index(fields=['store', 'is_active'], name='store_fixed_session_active_idx')],
            },
        ),
    ]
