# Generated by Django 5.2 on 2026-04-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_storefixedsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='webredemption',
            name='fixed_session_token',
            field=models.CharField(blank=True, db_index=True, help_text='Store-level fixed session token for table sticker QR flow', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='webredemption',
            name='session_token',
            field=models.CharField(db_index=True, help_text='The QRCodeSession.session_token from the scanned table QR', max_length=255),
        ),
    ]
