# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_webredemption_fixed_session_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webredemption',
            name='progress_applied',
            field=models.BooleanField(
                default=False,
                help_text='True once this web redemption has been synced to sharing progress for the phone owner',
            ),
        ),
    ]
