# Generated by Django 5.2 on 2026-04-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_webredemption_progress_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webredemption',
            name='progress_applied',
            field=models.BooleanField(default=False, help_text='Legacy: Web self-redemption no longer advances sharing lights; field retained for DB compatibility.'),
        ),
    ]
