# Generated by Django 5.2 on 2026-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_webredemption_progress_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontemplate',
            name='show_in_desk_qrcode',
            field=models.BooleanField(
                default=True,
                help_text='Whether template should be visible on desk QR web page',
            ),
        ),
    ]
