# Generated by Django 5.2 on 2026-04-16 08:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_web_redemption_legacy(apps, schema_editor):
    WebRedemption = apps.get_model('api', 'WebRedemption')
    CouponTemplate = apps.get_model('api', 'CouponTemplate')
    for wr in WebRedemption.objects.exclude(template_id=None).iterator():
        row = CouponTemplate.objects.filter(pk=wr.template_id).values('coupon_name').first()
        name = row['coupon_name'] if row else ''
        WebRedemption.objects.filter(pk=wr.pk).update(
            legacy_template_id=wr.template_id,
            legacy_template_coupon_name=name,
        )


def backfill_web_redemption_legacy_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_coupontemplate_show_in_desk_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='webredemption',
            name='legacy_template_coupon_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of template coupon_name; kept after template is deleted.', max_length=100),
        ),
        migrations.AddField(
            model_name='webredemption',
            name='legacy_template_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='CouponTemplate pk at time of redemption; kept after template is deleted.', null=True),
        ),
        migrations.RunPython(backfill_web_redemption_legacy, backfill_web_redemption_legacy_reverse),
        migrations.AlterField(
            model_name='webredemption',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_redemptions', to='api.coupontemplate'),
        ),
    ]
