# Generated by Django 5.2 on 2026-05-12 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_webredemption_legacy_template_set_null'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spinner_wallet', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gems', models.PositiveIntegerField(default=0)),
                ('cou_points', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spinner wallet',
                'verbose_name_plural': 'Spinner wallets',
                'db_table': 'spinner_wallet',
            },
        ),
        migrations.CreateModel(
            name='SpinnerRound',
            fields=[
                ('round_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=64)),
                ('num_players', models.PositiveSmallIntegerField()),
                ('g_total', models.PositiveSmallIntegerField()),
                ('f_floor', models.PositiveSmallIntegerField()),
                ('m_multiplier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shares', models.JSONField(default=list)),
                ('aborted', models.BooleanField(default=False)),
                ('abort_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spinner_round',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room_id', '-created_at'], name='spinner_rou_room_id_c69ac2_idx'), models.Index(fields=['aborted', '-created_at'], name='spinner_rou_aborted_34ae55_idx')],
            },
        ),
    ]
