# Generated by Django 5.2 on 2026-05-14 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_spinner_coop_wallet_round'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('spinner_solo', 'Spinner Solo'), ('spinner_coop', 'Spinner Co-op'), ('coupon_redeem', 'Coupon Redeem'), ('coupoint_spend', 'CouPoint Spend'), ('share_reward', 'Share Reward'), ('qr_claim', 'QR Claim'), ('seed', 'Starter Seed'), ('refund', 'Refund')], db_index=True, max_length=20)),
                ('delta_gems', models.IntegerField(default=0)),
                ('delta_cou_points', models.IntegerField(default=0)),
                ('balance_after_gems', models.PositiveIntegerField()),
                ('balance_after_cou_points', models.PositiveIntegerField()),
                ('related_round_id', models.UUIDField(blank=True, null=True)),
                ('related_coupon_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_store_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallet_tx_user_recent_idx'), models.Index(fields=['kind', '-created_at'], name='wallet_tx_kind_recent_idx')],
            },
        ),
    ]
