# Generated by Django 5.2 on 2026-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='URL to consumer avatar image', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Consumer display name', max_length=80, null=True),
        ),
    ]
