# Generated by Django 5.2 on 2026-05-14 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_studentprofile_display_name_and_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='api.store')),
            ],
            options={
                'db_table': 'store_news',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='store_news_store_recent_idx')],
            },
        ),
    ]
