# Generated by Django 5.2 on 2026-05-14 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_store_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['coupon_redeem', 'share_reward', 'qr_claim']), ('related_coupon_id__isnull', False)), fields=('user', 'kind', 'related_coupon_id'), name='wallet_tx_unique_coupon_event'),
        ),
    ]
