# Generated by Django 5.2 on 2026-05-21 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_wallet_tx_unique_coupon_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDrawAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('draw_probability', models.FloatField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('awarded_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.coupon')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_draw_attempts', to='api.coupontemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_draw_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_draw_attempt',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', '-attempted_at'], name='ddattempt_user_recent_idx')],
            },
        ),
    ]
