# Generated by Django 5.2 on 2026-05-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_dailydrawattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontemplate',
            name='gem_reward',
            field=models.PositiveIntegerField(default=1, help_text='Gems earned when this coupon is redeemed'),
        ),
    ]
