# Generated by Django 5.2 on 2026-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_coupontemplate_gem_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsharerequest',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Optional note from the sharer', max_length=80),
        ),
    ]
